name: Package and release

on:
    push:
        tags:
            - 'v**'
       
jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                cp LICENSE pack.png -t bleach/
                cp LICENSE pack.png -t bleach-language/
            - uses: actions/upload-artifact@v4
              with:
                name: bleach
                path: bleach/
                if-no-files-found: error
            - uses: actions/upload-artifact@v4
              with:
                name: bleach-language
                path: bleach-language/
    release-github:
        permissions:
            contents: write
        needs: package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                path: artifacts/
            - run: |
                mkdir release/
                zip -r release/bleach.zip artifacts/bleach/*
                zip -r release/bleach-language.zip artifacts/bleach-language/*
            - uses: softprops/action-gh-release@v2
              with:
                files: 'release/*'
